apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cedana-helm-helper-uninstaller
  labels:
    app.kubernetes.io/component: helper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: helper
  template:
    metadata:
      labels:
        app.kubernetes.io/component: helper
    spec:
      hostPID: true
      hostNetwork: true
      hostIPC: true
      containers:
        - name: binary-container
          image: cedana/cedana-helper:latest
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-volume
              mountPath: /host
              readOnly: false
          command: ["/bin/sh", "-c"]
          args: ["cedana k8s-helper destroy"]
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
