{{- if .Values.clusterMetrics.enabled -}}
{{- if include "cedana-helm.vectorEnabled" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: vector-aws-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  awsAccessKeyId: {{ dig "s3" "awsAccessKeyId" "" (.Values.clusterMetrics | default dict) | default .Values.config.awsAccessKeyId | default "" | quote }}
  awsSecretAccessKey: {{ dig "s3" "awsSecretAccessKey" "" (.Values.clusterMetrics | default dict) | default .Values.config.awsSecretAccessKey | default "" | quote }}
{{- end -}}
{{- end -}}
