apiVersion: v1
kind: Pod
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter
spec:
  containers:
    - name: jupyter-container
      image: cedana/jupyter-base:latest
      ports:
        - containerPort: 8888
      args:
        - start-notebook.sh
      env:
        - name: JUPYTER_TOKEN
          value: "helloworld" # Set your Jupyter token password here
  restartPolicy: OnFailure
