apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-restore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-restore
  template:
    metadata:
      labels:
        app: redis-restore
    spec:
      containers:
      - name: redis-restore
        image: redis:latest
        ports:
        - containerPort: 6379
        command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis-restore
  namespace: default
spec:
  selector:
    app: redis-restore
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---

