apiVersion: v1
kind: Pod
metadata:
  generateName: redis-example
  labels:
    app: redis
    kueue.x-k8s.io/queue-name: user-queue
  namespace: cedana
spec:
  runtimeClassName: cedana
  containers:
  - name: example-redis
    image: redis:6.2
    ports:
    - containerPort: 6379
    resources:
      requests:
        cpu: 0.5
