{{- if not .Values.config.preExistingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cedana-config
  labels:
    app: cedana-config
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  cluster-name: "{{ .Values.config.clusterName }}"
  url: "{{ .Values.config.url }}"
  sqs-queue-url: "{{ .Values.config.sqsQueueUrl }}"
  checkpoint-dir: "{{ .Values.config.checkpointDir }}"
  checkpoint-streams: "{{ .Values.config.checkpointStreams }}"
  checkpoint-compression: "{{ .Values.config.checkpointCompression }}"
  gpu-pool-size: "{{ .Values.config.gpuPoolSize }}"
  gpu-freeze-type: "{{ .Values.config.gpuFreezeType }}"
  gpu-shm-size: "{{ .Values.config.gpuShmSize }}"
  gpu-ld-lib-path: "{{ .Values.config.gpuLdLibPath }}"
  plugins-builds: "{{ .Values.config.pluginsBuilds }}"
  plugins-native-version: "{{ .Values.config.pluginsNativeVersion }}"
  plugins-criu-version: "{{ .Values.config.pluginsCriuVersion }}"
  plugins-runtime-shim-version: "{{ .Values.config.pluginsRuntimeShimVersion }}"
  plugins-gpu-version: "{{ .Values.config.pluginsGpuVersion }}"
  plugins-streamer-version: "{{ .Values.config.pluginsStreamerVersion }}"
  metrics-otel: "{{ .Values.config.metricsOtel }}"
  profiling-enabled: "{{ .Values.config.profilingEnabled }}"
  log-level: "{{ .Values.config.logLevel }}"
{{- end }}
