{{- if not .Values.config.preExistingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cedana-config
  labels:
    app: cedana-config
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  cluster-id: "{{ required "Please provide --set config.clusterId=<cluster-id>" .Values.config.clusterId }}"
  url: "{{ required "Please provide --set config.url=<cedana-url>" .Values.config.url }}"
  address: "{{ required "Please provide --set config.address=<daemon-address>" .Values.config.address }}"
  protocol: "{{ required "Please provide --set config.protocol=<daemon-protocol>" .Values.config.protocol }}"
  sqs-queue-url: "{{ .Values.config.sqsQueueUrl }}"
  checkpoint-dir: "{{ .Values.config.checkpointDir }}"
  checkpoint-streams: "{{ .Values.config.checkpointStreams }}"
  checkpoint-compression: "{{ .Values.config.checkpointCompression }}"
  gpu-pool-size: "{{ .Values.config.gpuPoolSize }}"
  gpu-freeze-type: "{{ .Values.config.gpuFreezeType }}"
  gpu-shm-size: "{{ .Values.config.gpuShmSize }}"
  gpu-ld-lib-path: "{{ .Values.config.gpuLdLibPath }}"
  plugins-builds: "{{ .Values.config.pluginsBuilds }}"
  plugins-native-version: "{{ .Values.config.pluginsNativeVersion }}"
  plugins-criu-version: "{{ .Values.config.pluginsCriuVersion }}"
  plugins-containerd-runtime-version: "{{ .Values.config.pluginsContainerdRuntimeVersion }}"
  plugins-gpu-version: "{{ .Values.config.pluginsGpuVersion }}"
  plugins-streamer-version: "{{ .Values.config.pluginsStreamerVersion }}"
  metrics: "{{ .Values.config.metrics }}"
  profiling: "{{ .Values.config.profiling }}"
  log-level: "{{ .Values.config.logLevel }}"

  aws-access-key-id: "{{ .Values.config.awsAccessKeyId }}"
  aws-region: "{{ .Values.config.awsRegion }}"

  containerd-address: "{{ .Values.config.containerdAddress }}"

  shm-config-enabled: "{{ .Values.shmConfig.enabled }}"
  shm-config-size: "{{ .Values.shmConfig.size }}"
  shm-config-min-size: "{{ .Values.shmConfig.minSize }}"
{{- end }}
