{{- if eq .Values.config.checkpointDir "csx://" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cedana-helm.csxConfigMapName" . }}
  labels:
    app.kubernetes.io/component: csx
    {{- include "cedana-helm.labels" . | nindent 4 }}
data:
  csx-log-level: "{{ .Values.csx.logLevel }}"
  csx-sock-addr: "{{ .Values.csx.sockAddr }}"
  csx-memory-cache-percent: "{{ .Values.csx.memoryCachePercent }}"
  csx-memory-cache-path: "{{ .Values.csx.memoryCachePath }}"
  csx-local-disk-cache-limit: "{{ .Values.csx.localDiskCacheLimit }}"
  csx-local-disk-cache-path: "{{ .Values.csx.localDiskCachePath }}"
  csx-nfs-path: "{{ required "Please provide --set csx.nfsPath=<nfs-path> when config.checkpointDir=csx://" .Values.csx.nfsPath }}"
  csx-nfs-poll-interval: "{{ .Values.csx.nfsPollInterval }}"
  csx-tmp-dir: "{{ .Values.csx.tmpDir }}"
  csx-tmp-dir-object-limit: "{{ .Values.csx.tmpDirObjectLimit }}"
  csx-enable-metrics: "{{ .Values.csx.enableMetrics }}"
  csx-read-timeout: "{{ .Values.csx.readTimeout }}"
  csx-write-timeout: "{{ .Values.csx.writeTimeout }}"
  csx-initialization-timeout: "{{ .Values.csx.initializationTimeout }}"
{{- end }}
