apiVersion: v1
kind: Service
metadata:
  name: cedana-daemon-grpc-service
spec:
  selector:
    app: binary-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: grpc
      nodePort: 31000
  type: NodePort
