{{- if .Values.daemonHelper.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cedana-helm.daemonHelperServiceAccountName" . }}
  labels:
    app.kubernetes.io/component: helper
    {{- include "cedana-helm.labels" . | nindent 4 }}
  {{- with .Values.daemonHelper.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.daemonHelper.serviceAccount.automount }}
{{- end }}
