apiVersion: v1
kind: Service
metadata:
  name: {{ include "cedana-helm.fullname" . }}-helper-service
  labels:
    {{- include "cedana-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: helper
  {{- with .Values.daemonHelper.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "cedana-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: helper
  ports:
    - protocol: TCP
      port: {{ .Values.daemonHelper.service.port }}
      targetPort: {{ .Values.daemonHelper.service.targetPort }}
      {{- if .Values.daemonHelper.service.nodePort }}
      nodePort: {{ .Values.daemonHelper.service.nodePort }}
      {{- end }}
  type: {{ .Values.daemonHelper.service.type }}
