---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cedana-helm.fullname" . }}
  labels:
    app.kubernetes.io/component: helper
    app.kubernetes.io/created-by: cedana-helm
    app.kubernetes.io/part-of: cedana-helm
    {{- include "cedana-helm.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.daemonHelper.updateStrategy.maxSurge }}
      maxUnavailable: {{ .Values.daemonHelper.updateStrategy.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: helper
      {{- include "cedana-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: binary-app
        app.kubernetes.io/component: helper
        {{- include "cedana-helm.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      hostNetwork: true
      hostIPC: true
      containers:
        - name: binary-container
          image: {{ .Values.daemonHelper.image.repository }}:{{ .Values.daemonHelper.image.tag }}
          imagePullPolicy: {{ .Values.daemonHelper.image.imagePullPolicy }}
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-volume
              mountPath: /host
              readOnly: false
          command: ["/bin/sh", "-c"]
          args: ["cedana k8s-helper --setup-host true && sleep infinity"]
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 200
            periodSeconds: 20
          startupProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 20
          readinessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 20
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "cedana k8s-helper destroy"]
          env:
            - name: SIGNOZ_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cedana-secrets
                  key: signoz-api-key
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
