---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cedana-helm.fullname" . }}-helper
  labels:
    app.kubernetes.io/component: helper
    app.kubernetes.io/created-by: cedana-helm
    app.kubernetes.io/part-of: cedana-helm
    {{- include "cedana-helm.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.daemonHelper.updateStrategy.maxSurge }}
      maxUnavailable: {{ .Values.daemonHelper.updateStrategy.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: helper
      {{- include "cedana-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: helper
        {{- include "cedana-helm.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      containers:
        - name: binary-container
          image: {{ .Values.daemonHelper.image.repository }}:{{ .Values.daemonHelper.image.tag }}
          imagePullPolicy: {{ .Values.daemonHelper.image.imagePullPolicy }}
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-volume
              mountPath: /host
              readOnly: false
          command: ["/bin/sh", "-c"]
          {{ if .Values.daemonHelper.upgradeAndRestart }}
          args: ["cedana k8s-helper --restart true --start-otelcol {{ .Values.startOtelcol }} --port {{ (index .Values.daemonHelper.service.ports 0).targetPort }} && sleep infinity"]
          {{ else }}
          args: ["cedana k8s-helper --setup-host true --start-otelcol {{ .Values.startOtelcol }} --port {{ (index .Values.daemonHelper.service.ports 0).targetPort }} && sleep infinity"]
          {{ end }}
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          env:
            - name: SIGNOZ_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "cedana-helm.cedanaSecretName" . }}
                  key: signoz-access-token
            - name: CEDANA_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "cedana-helm.cedanaSecretName" . }}
                  key: cedana-auth-token
            - name: CEDANA_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "cedana-helm.cedanaSecretName" . }}
                  key: cedana-url
            - name: CEDANA_CONTROLLER_SERVICE
              value: {{ include "cedana-helm.fullname" . }}-manager-service
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
      {{- with .Values.daemonHelper.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonHelper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
