apiVersion: v1
kind: Service
metadata:
  name: cedana-daemon-grpc-service
  labels:
  {{- include "cedana-helm.labels" . | nindent 4 }}
  {{- with .Values.daemonHelper.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: binary-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort
