apiVersion: v1
kind: Service
metadata:
  name: {{ include "cedana-helm.fullname" . }}-manager-service
  labels:
    {{- include "cedana-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  {{- with .Values.controllerManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "cedana-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  ports:
    {{- .Values.controllerManager.service.ports | toYaml | nindent 4 }}
