apiVersion: v1
kind: Service
metadata:
  name: cedana-manager-service
  labels:
  {{- include "cedana-helm.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: cedana-manager
  ports:
	{{- .Values.controllerManager.service.ports | toYaml | nindent 2 }}
