apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cedana-operator-chart.fullname" . }}-manager-role
  labels:
  {{- include "cedana-operator-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - core.cedana.ai
  resources:
  - cedanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.cedana.ai
  resources:
  - cedanas/finalizers
  verbs:
  - update
- apiGroups:
  - core.cedana.ai
  resources:
  - cedanas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cedana-operator-chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cedana-operator
    app.kubernetes.io/part-of: cedana-operator
  {{- include "cedana-operator-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cedana-operator-chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cedana-operator-chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
