apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cedana-helm.fullname" . }}-manager-role
  labels:
  {{- include "cedana-helm.labels" . | nindent 4 }}
rules:
{{ if .Values.installKueue }}
- apiGroups:
  - "kueue.x-k8s.io"
  resources:
  - workloads
  - localqueues
  - clusterqueues
  - resourceflavours
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "kueue.x-k8s.io/v1beta1"
  resources:
  - workloads
  - localqueues
  - clusterqueues
  - resourceflavours
  verbs:
  - get
  - list
  - watch
{{ end }}
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - "apps"
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
- apiGroups:
  - "core.cedana.ai"
  resources:
  - cedanaworkloads
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "core.cedana.ai"
  resources:
  - cedanaworkloads/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - "core.cedana.ai"
  resources:
  - cedanaworkloads/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cedana-helm.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cedana-helm
    app.kubernetes.io/part-of: cedana-helm
  {{- include "cedana-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cedana-helm.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cedana-helm.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
