apiVersion: v1
kind: Service
metadata:
  name: {{ include "cedana-helm.fullname" . }}-controller-metrics
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cedana-helm
    app.kubernetes.io/part-of: cedana-helm
  {{- include "cedana-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/component: manager
  {{- include "cedana-helm.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.metricsService.ports | toYaml | nindent 4 }}
