{{- if .Values.runtimeClass.create }}
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ include "cedana-helm.runtimeClassName" . }}
handler: {{ .Values.runtimeClass.handler }}
{{- end }}
