{{- if not .Values.config.preExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cedana-helm.secretName" . }}
  labels:
    app: {{ template "cedana-helm.secretName" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  auth-token: "{{ required "Please provide --set config.authToken=<cedana-auth-token>" .Values.config.authToken | b64enc }}"
  {{- if .Values.config.awsSecretAccessKey }}
  aws-secret-access-key: "{{ .Values.config.awsSecretAccessKey | b64enc }}"
  {{- else }}
  aws-secret-access-key: ""
  {{- end }}
{{- end }}
