apiVersion: v1
kind: Secret
metadata:
  name: cedana-secrets
  labels:
    app: cedana-secrets
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  signoz-api-key: "{{ .Values.cedanaConfig.signozApiKey | b64enc }}"
