{{- if not .Values.config.preExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: cedana-secrets
  labels:
    app: cedana-secrets
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  auth-token: "{{ .Values.config.authToken | b64enc }}"
  aws-secret-access-key: "{{ .Values.config.awsSecretAccessKey | b64enc }}"
{{- end }}
