{{- if not .Values.cedanaConfig.preExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: cedana-secrets
  labels:
    app: cedana-secrets
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  signoz-access-token: "{{ .Values.cedanaConfig.signozAccessToken | b64enc }}"
  cedana-auth-token: "{{ .Values.cedanaConfig.cedanaAuthToken | b64enc }}"
  cedana-cluster-name: "{{ .Values.cedanaConfig.cedanaClusterName | b64enc }}"
  cedana-url: "{{ .Values.cedanaConfig.cedanaUrl | b64enc }}"
  cedana-url: "{{ .Values.cedanaConfig.cedanaSqsQueueUrl | b64enc }}"
{{- end }}
