apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cedana-operator-chart.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cedana-operator
    app.kubernetes.io/part-of: cedana-operator
  {{- include "cedana-operator-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}