apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cedana-helm.fullname" . }}-uninstaller-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cedana-helm.fullname" . }}-uninstaller-role
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cedana-helm.fullname" . }}-uninstaller-clusterrole
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cedana-helm.fullname" . }}-uninstaller-rb
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep
subjects:
  - kind: ServiceAccount
    name: {{ include "cedana-helm.fullname" . }}-uninstaller-sa
roleRef:
  kind: Role
  name: {{ include "cedana-helm.fullname" . }}-uninstaller-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cedana-helm.fullname" . }}-uninstaller-crb
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep
subjects:
  - kind: ServiceAccount
    name: {{ include "cedana-helm.fullname" . }}-uninstaller-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cedana-helm.fullname" . }}-uninstaller-clusterrole
  apiGroup: rbac.authorization.k8s.io
