apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cedana-helm.fullname" . }}-uninstaller
  labels:
    app.kubernetes.io/component: uninstaller
    app.kubernetes.io/created-by: cedana-helm
    app.kubernetes.io/part-of: cedana-helm
    {{- include "cedana-helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: uninstaller
      {{- include "cedana-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: uninstaller
        {{- include "cedana-helm.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cedana-helm.fullname" . }}-uninstaller-sa
      hostPID: true
      hostIPC: true
      initContainers:
        - name: uninstaller
          image: {{ .Values.daemonHelper.image.repository }}:{{ .Values.daemonHelper.image.tag }}
          imagePullPolicy: {{ .Values.daemonHelper.image.imagePullPolicy }}
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-volume
              mountPath: /host
              readOnly: false
          command: ["/bin/sh", "-c"]
          args: ["cedana k8s-helper destroy"]
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              SELECTOR="app.kubernetes.io/component=uninstaller";
              POD_NAME=$(hostname);
              echo "Waiting for all DaemonSet pods to be Ready...";
              until [ "$(kubectl get pods -l $SELECTOR -n $POD_NAMESPACE -o json | jq '[.items[] | select(.status.phase=="Running")] | length')" -eq "$(kubectl get nodes --no-headers | wc -l)" ]; do
                echo "Not all pods ready yet...";
                sleep 2;
              done;

              echo "All pods are ready. Determining leader...";
              LEADER=$(kubectl get pods -l $SELECTOR -n $POD_NAMESPACE -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | sort | head -n 1);

              echo "Leader determined: $LEADER";
              echo "Current pod: $POD_NAME";

              if [ "$POD_NAME" = "$LEADER" ]; then
              echo "I am the leader ($POD_NAME), deleting the DaemonSet...";
              kubectl delete daemonset cedana-uninstaller -n $POD_NAMESPACE;
              else
              echo "Not the leader ($POD_NAME), exiting.";
              fi
              sleep 5
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
