apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cedana-helm.fullname" . }}-uninstaller
  labels:
    app.kubernetes.io/component: uninstaller
    app.kubernetes.io/created-by: cedana-helm
    app.kubernetes.io/part-of: cedana-helm
    {{- include "cedana-helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: uninstaller
      {{- include "cedana-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: uninstaller
        {{- include "cedana-helm.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cedana-helm.fullname" . }}-uninstaller-sa
      hostPID: true
      hostNetwork: true
      hostIPC: true
      initContainers:
        - name: uninstaller
          image: {{ .Values.daemonHelper.image.repository }}:{{ .Values.daemonHelper.image.tag }}
          imagePullPolicy: {{ .Values.daemonHelper.image.imagePullPolicy }}
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-volume
              mountPath: /host
              readOnly: false
          command: ["/bin/sh", "-c"]
          args: ["cedana k8s-helper destroy"]
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Deleting remaining Cedana resources...";
              kubectl delete daemonset {{ include "cedana-helm.fullname" . }}-uninstaller -n ${POD_NAMESPACE} --wait=false;
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
