apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cedana-uninstaller
  labels:
    app.kubernetes.io/component: cedana-uninstaller
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/resource-policy: keep
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: cedana-uninstaller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cedana-uninstaller
    spec:
      hostPID: true
      hostNetwork: true
      hostIPC: true
      containers:
        - name: binary-container
          image: {{ .Values.daemonHelper.image.repository }}:{{ .Values.daemonHelper.image.tag }}
          imagePullPolicy: {{ .Values.daemonHelper.image.imagePullPolicy }}
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-volume
              mountPath: /host
              readOnly: false
          command: ["/bin/sh", "-c"]
          args: ["cedana k8s-helper destroy"]
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
