name: Check

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      helm:
        type: boolean
        description: "Check helm charts"
        required: false
        default: false
      version:
        type: boolean
        description: "Check version"
        required: false
        default: false

jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest
    if: inputs.helm
    steps:
      - uses: actions/checkout@v3

      - name: Lint helm chart
        run: |
          helm lint cedana-helm

  version:
    name: Version
    runs-on: ubuntu-latest
    if: inputs.version
    steps:
      - uses: actions/checkout@v4

      - name: Write release version
        id: version
        run: |
          VERSION=${{ github.head_ref || github.ref_name }}
          # strip v
          echo Version: ${VERSION#v}
          echo "VERSION=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Check helm versions
        run: |
          grep -qF '${{ steps.version.outputs.VERSION }}' cedana-helm/Chart.yaml || (echo "update the version field in cedana-helm/Chart.yaml"; exit 1)
