name: Check

on:
  workflow_call:
    inputs:
      pr_title:
        type: boolean
        description: "Pull request title"
        required: false
        default: false
      helm:
        type: boolean
        description: "Check helm charts"
        required: false
        default: false
      version:
        type: boolean
        description: "Check version"
        required: false
        default: false

permissions:
  contents: read

jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest
    if: inputs.helm
    steps:
      - uses: actions/checkout@v3

      - name: Lint helm chart
        run: |
          helm lint cedana-helm

  pr-title:
    name: PR Title
    if: inputs.pr_title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $TITLE"
          if [[ ! "$TITLE" =~ ^CED-[0-9]+:\  ]]; then
            echo "❌ PR title must start with 'CED-<number>: ' (note the colon and space)"
            exit 1
          fi

  version:
    name: Version
    runs-on: ubuntu-latest
    if: inputs.version
    steps:
      - uses: actions/checkout@v4

      - name: Write release version
        id: version
        run: |
          VERSION=${{ github.head_ref || github.ref_name }}
          # strip v
          echo Version: ${VERSION#v}
          echo "VERSION=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Check helm versions
        run: |
          grep -qF '${{ steps.version.outputs.VERSION }}' cedana-helm/Chart.yaml || (echo "update the version field in cedana-helm/Chart.yaml"; exit 1)
