name: PR to Main Branch

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  helm-lint:
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@v3
      - name: Lint helm chart
        run: |
          helm lint cedana-helm

  install-test:
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v3
      - name: Use Docker
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      # check if this uses docker image
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind

      - name: install helm chart
        run: |
          helm install cedana ./cedana-helm --create-namespace -n cedana-operator-system \
              --set cedanaConfig.cedanaAuthToken="${CEDANA_API_KEY}" \
              --set cedanaConfig.cedanaUrl="https://sandbox.cedana.ai"
          kubectl wait --timeout=1m --for=condition=Ready pod -A -l app.kubernetes.io/component=manager
