name: PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint helm chart
        run: |
          helm lint cedana-helm

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CEDANA_URL: ${{ vars.CEDANA_URL }}
      CEDANA_AUTH_TOKEN: ${{ secrets.CEDANA_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Docker
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind

      - name: Install and test
        run: |
          helm install cedana ./cedana-helm --create-namespace -n cedana-operator-system \
              --set cedanaConfig.cedanaUrl="${CEDANA_URL}" \
              --set cedanaConfig.cedanaAuthToken="${CEDANA_AUTH_TOKEN}"
          kubectl wait --for=jsonpath='{.status.phase}'=Running --all pod -n cedana-operator-system
