name: Publish

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write
  pull-requests: write
  checks: write

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        description: "Run with debugging enabled"
        required: false
        default: false
      github:
        type: boolean
        description: "Publish to GitHub releases"
        required: false
        default: false
      dockerhub:
        type: boolean
        description: "Publish images to Docker Hub"
        required: false
        default: false
      chart_name:
        type: string
        description: "Name of the chart to publish"
        required: false
        default: cedana-helm
      post_summary:
        type: boolean
        description: "Post summary to Slack"
        required: false
        default: false

jobs:
  github:
    name: GitHub
    needs: dockerhub
    runs-on: ubuntu-latest
    if: inputs.github
    steps:
      - uses: runs-on/action@v1

      - name: Create release
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.head_ref || github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag" \
              --generate-notes

  dockerhub:
    name: DockerHub
    runs-on: ubuntu-latest
    if: inputs.dockerhub
    steps:
      - uses: actions/checkout@v4

      - name: Write release version
        id: version
        run: |
          VERSION=${{ github.head_ref || github.ref_name }}
          # strip v
          echo Version: ${VERSION#v}
          echo "VERSION=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Push helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: cedana-helm
          repository: cedana
          tag: ${{ steps.version.outputs.VERSION }}
          registry: registry.hub.docker.com
          path: ${{ inputs.chart_name }}
          registry_username: ${{ vars.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}

  post-summary:
    name: Post Summary
    runs-on: ubuntu-latest
    needs: ["github", "dockerhub"]
    if: inputs.post_summary
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          fetch-tags: true

      - name: Get tag
        id: tag
        run: |
          echo "tag=$(git tag --sort=-creatordate | sed -n '1p')" >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: previous-tag
        run: |
          echo "tag=$(git tag --sort=-creatordate | sed -n '2p')" >> $GITHUB_OUTPUT

      - name: Post summary
        uses: cedana/cedana-publish-summary@v1
        with:
          title: cedana-helm-charts
          tag: ${{ steps.tag.outputs.tag }}
          previous-tag: ${{ steps.previous-tag.outputs.tag }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_RELEASE }}
