name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Run with debugging enabled"
        required: false
        default: false

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload helm chart
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: cedana-helm

  download:
    name: Download
    uses: cedana/cedana/.github/workflows/download.yml@main
    secrets: inherit
    with:
      cedana_version: main
      criu_version: release
      gpu_version: main
      streamer_version: main
      controller_version: staging
      runtime_shim_version: release

  test:
    name: Test
    uses: cedana/cedana/.github/workflows/test_k8s.yml@main
    needs: [prepare, download]
    secrets: inherit
    with:
      ref: main
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug }}
      post_summary: false
