name: release

on:
  workflow_call:
    inputs:
      ref:
        description: "ref to build eg v0.8.0"
        required: false
        type: string
      version:
        description: "push helm chart with this version, eg v0.8.0"
        type: string
  workflow_dispatch:
    inputs:
      ref:
        description: "ref to build eg v0.8.0"
        required: false
        type: string
      version:
        description: "push helm chart with this version, eg v0.8.0"
        type: string

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ inputs.ref }}
      - name: Write release version
        id: version
        run: |
          VERSION=${{ inputs.version }}
          echo Version: ${VERSION#v}
          echo "VERSION=${VERSION#v}" >> "$GITHUB_OUTPUT"
      - name: Check helm versions
        run: |
          grep -qF '${{ steps.version.outputs.VERSION }}' chart/Chart.yaml
      - name: Lint helm chart
        run: |
          helm lint chart
      - name: Push helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: cedana-helm
          repository: cedana
          tag: ${{ steps.version.outputs.VERSION }}
          registry: registry-1.docker.io
          path: chart
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
