name: Release

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write
  pull-requests: write
  checks: write

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      debug_test:
        type: boolean
        description: "Run tests with debugging enabled"
        required: false
        default: false
      debug_publish:
        type: boolean
        description: "Run publish with debugging enabled"
        required: false
        default: false

concurrency:
  group: release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets: inherit
    with:
      helm: true
      version: true

  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml
    needs: check
    secrets: inherit

  download:
    name: Download
    uses: cedana/cedana/.github/workflows/download.yml@main
    needs: prepare
    secrets: inherit
    with:
      cedana_version: ${{ needs.prepare.outputs.cedana_version }}
      controller_version: ${{ needs.prepare.outputs.controller_version }}
      runtime_shim_version: ${{ needs.prepare.outputs.runtime_shim_version }}
      criu_version: ${{ needs.prepare.outputs.criu_version }}
      gpu_version: ${{ needs.prepare.outputs.gpu_version }}
      streamer_version: ${{ needs.prepare.outputs.streamer_version }}

  k3s:
    name: Kubernetes
    uses: cedana/cedana/.github/workflows/test_k8s.yml@main
    needs: [prepare, download]
    secrets: inherit
    with:
      ref: main
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug }}
      post_summary: true

  eks:
    name: Kubernetes
    uses: cedana/cedana/.github/workflows/test_k8s.yml@main
    needs: [prepare, download]
    secrets: inherit
    concurrency: test-k8s-eks # Since the cluster is reused
    with:
      ref: main
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug }}
      platform: EKS
      post_summary: true

  gke:
    name: Kubernetes
    uses: cedana/cedana/.github/workflows/test_k8s.yml@main
    needs: [prepare, download]
    secrets: inherit
    concurrency: test-k8s-gke # Since the cluster is reused
    with:
      ref: main
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug }}
      platform: GKE
      post_summary: true

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    needs: [test]
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_publish }}
      github: true
      dockerhub: true
      post_summary: true
