name: release

on:
  push:
    tags:
      - v*

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write release version
        id: version
        run: |
          VERSION=${{ github.ref_name }}
          # strip v
          echo Version: ${VERSION#v}
          echo "VERSION=${VERSION#v}" >> "$GITHUB_OUTPUT"
      - name: Check helm versions
        run: |
          grep -qF '${{ steps.version.outputs.VERSION }}' cedana-helm/Chart.yaml || (echo "update the version field in cedana-helm/Chart.yaml"; exit 1)
      - name: Lint helm chart
        run: |
          helm lint cedana-helm
      - name: Push helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: cedana-helm
          repository: cedana
          tag: ${{ steps.version.outputs.VERSION }}
          registry: registry-1.docker.io
          path: cedana-helm
          registry_username: ${{ vars.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
      - uses: ncipollo/release-action@v1
